version: "3.9"
services:
    frontend:
        build:
            context: ./frontend
        # volumes:
        #     - ./frontend/public:containerPath:ro
        #     - ./frontend/src:containerPath:ro
        # ports:
        #     - "3000:3000"
        expose:
            - 3000
        container_name: frontend
        depends_on:
            - backend

    backend:
        build:
            context: ./backend
        ports:
            - "5000:5000"
        # expose:
        #     - 5000
        container_name: backend
        depends_on:
            - db

    proxy:
        restart: always
        build:
            context: ./proxy
        container_name: proxy_nginx
        ports:
            - "8080:80"
        depends_on:
            - frontend
            - backend

    db:
    image: mariadb
    restart: always
    env_file:
      - ./.env